export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const REGISTER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_USER_FAIL";


export const LOAD_REQUEST = "LOAD_USER_REQUEST";
export const LOAD_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_FAIL = "LOAD_USER_FAIL";


export const LOGOUT_SUCCESS = "LOGOUT_USER_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_USER_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS"
export const GENERATE_SUMMARY_REQUEST = "GENERATE_SUMMARY_REQUEST";
export const GENERATE_SUMMARY_SUCCESS = "GENERATE_SUMMARY_SUCCESS";
export const GENERATE_SUMMARY_FAILURE = "GENERATE_SUMMARY_FAILURE";
export const GET_HISTORY_REQUEST= "GET_HISTORY_REQUEST";
export const GET_HISTORY_SUCCESS = "GET_HISTORY_SUCCESS";
export const GET_HISTORY_FAILURE = "GET_HISTORY_FAILURE";
